name: wschosta
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74064
title: Walter G Schostak
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#b2cae4'
    - '#0f203c'
    - '#15468b'
    - '#7d9fc5'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
