name: wschosta
favicon: null
layout_spectrum: 0.9950215148273855
typography_spectrum: 0.9357047942467034
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5878706558141857
  lightness: 0.96187141421251
  saturation: 0.35432209237478673
  rhythmicContrast: 0.3322160798124969
purpose: []
